export const carTypesData = {
  car_types: [
    {
      type: "SUV",
      models: [
        "Toyota RAV4",
        "Honda CR-V",
        "Ford Explorer",
        "Jeep Grand Cherokee",
        "Hyundai Tucson",
        "Kia Sportage",
        "Chevrolet Tahoe",
        "Nissan Rogue",
      ],
    },
    {
      type: "Sedan",
      models: [
        "Toyota Corolla",
        "Honda Accord",
        "Hyundai Elantra",
        "Mazda 6",
        "Nissan Altima",
        "Volkswagen Passat",
        "Kia K5",
        "Subaru Legacy",
      ],
    },
    {
      type: "Hatchback",
      models: [
        "Volkswagen Golf",
        "Ford Fiesta",
        "Honda Fit",
        "Toyota Yaris",
        "Hyundai i20",
        "Mazda 3",
        "Chevrolet Spark",
        "Renault Clio",
      ],
    },
    {
      type: "Pickup",
      models: [
        "Toyota Hilux",
        "Ford Ranger",
        "Isuzu D-Max",
        "Nissan Navara",
        "Chevrolet Colorado",
        "Mitsubishi L200",
        "GMC Sierra",
        "Ram 1500",
      ],
    },
    {
      type: "Luxury",
      models: [
        "Mercedes-Benz E-Class",
        "BMW 5 Series",
        "Audi A6",
        "Lexus ES",
        "Jaguar XF",
        "Tesla Model S",
        "Genesis G80",
        "Volvo S90",
      ],
    },
    {
      type: "Van",
      models: [
        "Toyota Hiace",
        "Ford Transit",
        "Nissan NV350",
        "Mercedes-Benz Vito",
        "Renault Trafic",
        "Hyundai H-1",
        "Volkswagen Transporter",
        "Peugeot Expert",
      ],
    },
    {
      type: "Convertible",
      models: [
        "Mazda MX-5 Miata",
        "BMW Z4",
        "Porsche 911 Cabriolet",
        "Audi A5 Cabriolet",
        "Mercedes-Benz C-Class Cabriolet",
        "Ford Mustang Convertible",
        "Chevrolet Camaro Convertible",
        "Mini Cooper Convertible",
      ],
    },
    {
      type: "Coupe",
      models: [
        "Ford Mustang",
        "Chevrolet Camaro",
        "BMW 4 Series",
        "Audi A5",
        "Mercedes-Benz CLA",
        "Dodge Challenger",
        "Nissan 370Z",
        "Toyota GR86",
      ],
    },
    {
      type: "Crossover",
      models: [
        "Subaru Crosstrek",
        "Kia Seltos",
        "Toyota C-HR",
        "Mazda CX-30",
        "Hyundai Kona",
        "Nissan Kicks",
        "Chevrolet Trailblazer",
        "Honda HR-V",
      ],
    },
    {
      type: "Electric",
      models: [
        "Tesla Model 3",
        "Tesla Model Y",
        "Nissan Leaf",
        "Hyundai Ioniq 5",
        "Kia EV6",
        "Ford Mustang Mach-E",
        "BMW i4",
        "Volkswagen ID.4",
      ],
    },
    {
      type: "Minivan",
      models: [
        "Toyota Sienna",
        "Honda Odyssey",
        "Chrysler Pacifica",
        "Kia Carnival",
        "Nissan Quest",
        "Dodge Grand Caravan",
        "Ford Galaxy",
        "Volkswagen Sharan",
      ],
    },
    {
      type: "Sports Car",
      models: [
        "Porsche 911",
        "Chevrolet Corvette",
        "Ford Mustang GT",
        "Toyota Supra",
        "Audi TT",
        "Nissan GT-R",
        "BMW M4",
        "Jaguar F-Type",
      ],
    },
  ],
};
