"use client";
import React, { FC } from "react";
import { CrownOutlined } from "@ant-design/icons";
import { Card } from "antd";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";
import LinkButton from "../buttons/linkButton";
import { TopRevenueService } from "@/app/api/analytics/adminApi/action";

interface TopCustomersListProps {
  servicesRevenue: TopRevenueService[];
}

const TopAdminRevenueServiceList: FC<TopCustomersListProps> = ({
  servicesRevenue,
}) => {
  return (
    <Card
      title={
        <div className="flex w-full items-center justify-between gap-2 text-lg font-semibold text-primaryBlue">
          <CrownOutlined /> Top Revenue Generated By Service Type
          <LinkButton link="/service" />
        </div>
      }
      className="shadow-md rounded-xl"
    >
      {servicesRevenue.length <= 0 ? (
        <div className="min-h-80 font-bold text-primaryGreen text-xl flex items-center justify-center">
          {" "}
         No Revenue Data Available {" "}
        </div>
      ) : (
        <div className="w-full h-72">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={servicesRevenue}>
              <XAxis dataKey="service_type" tick={{ fontSize: 12 }} />
              <YAxis />
              <Tooltip
                formatter={(value: any) =>
                  typeof value === "number"
                    ? `${value.toLocaleString()} Rwf`
                    : value + "Rwf"
                }
              />
              <Legend />
              <Bar
                dataKey="total_revenue"
                name="Total Revenue"
                fill="#f59e0b"
              />
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}
    </Card>
  );
};

export default TopAdminRevenueServiceList;
